meson: Disallow flashrom if not found
If libflashrom is allowed but not actually available, we otherwise fail
the build:

../plugins/flashrom/fu-flashrom-plugin.c:10:10: fatal error: libflashrom.h: No such file or directory
   10 | #include <libflashrom.h>
      |          ^~~~~~~~~~~~~~~

(cherry picked from commit 49ef4486ba384a4303d1367ed78380c5d1770e34)