Install meson 1.11 with pipx
Required for the Rust workspace support but it's a bit tricky to get
right across all distributions. As of PEP668 pipx is the recommended way
to install tools system-wide but we have to --force it to actually
overwrite an existing /usr/bin/foo.

And we do have to overwrite because our scripts rely on other parts
packged by the distributions' meson packages (e.g. rpmmacros).

The exception is Centos which doesn't have pipx. On that we use normal
pip but still overwrite the package. We have to move the whole
site-packages dir out of the way, otherwise we get conflicts:
    ImportError: cannot import name 'default_datadir' from 'mesonbuild.mesonlib'
    (/usr/lib/python3.9/site-packages/mesonbuild/mesonlib/__init__.py)