trivial: Disallow Qt short keywords in the Qt thread test
clang-format wants to shuffle the header down to below the Qt includes,
resulting in a compiler error:

In file included from /usr/include/qt5/QtCore/qobject.h:46,
                 from /usr/include/qt5/QtCore/qcoreapplication.h:46,
                 from /usr/include/qt5/QtCore/QCoreApplication:1,
                 from ../qt-thread-test.cpp:10:
/usr/include/qt5/QtCore/qobjectdefs.h:93:20: error: expected unqualified-id before ‘public’
   93 | # define Q_SIGNALS public QT_ANNOTATE_ACCESS_SPECIFIER(qt_signal)
      |                    ^~~~~~
/usr/include/qt5/QtCore/qobjectdefs.h:89:22: note: in expansion of macro ‘Q_SIGNALS’
   89 | #     define signals Q_SIGNALS
      |                      ^~~~~~~~~
/usr/include/glib-2.0/gio/gdbusintrospection.h:157:25: note: in expansion of macro ‘signals’
  157 |   GDBusSignalInfo     **signals;

The error is caused by Qt defining `signals` and GLib getting confused
by that #define. Since this is only a test anyway prevent Qt from
defining those short keywords, we're not actually using them anyway.

With this is in place we can now keep the clang-format header order.