meson: Add the subproject's libxmlb GIR include path
When building libxmlb as a subproject, its GIR files end up in
subprojects/libxmlb/src/ and we need to include that path (clumsily so)
to avoid
    ERROR: Could not find GIR dependency in the search paths: Xmlb-2.0