rust: Switch to thiserror@1
Notably: this uses thiserror version 1 and not the current 2.0.19 due to
this build error:

    error: environment variable `CARGO_PKG_VERSION_PATCH` not defined at compile time
    --> ../../subprojects/thiserror-impl-2.0.19/src/lib.rs:51:34
    |
    51 |             concat!("__private", env!("CARGO_PKG_VERSION_PATCH")),
    |                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: `CARGO_PKG_VERSION_PATCH` may not be available for the current Cargo target
    = help: Cargo sets build script variables at run time. Use `std::env::var("CARGO_PKG_VERSION_PATCH")` instead

    error: aborting due to 1 previous error

thiserror requires CARGO_PKG_VERSION_PATCH to be set in the env, the
value of which is used as private field in case there are multiple versions
of thiserror in a workspace. cargo sets that variable by default but
meson does not and it does not provide a way to pass that environment
variable down to rustc.