Don't generate vapi during cross builds
This currently fails on the s390x cross builds and may be caused
by dependencies but since the total number of vala users on s390x is
zero anyway, let's just skip it.

Error in the CI:

/usr/bin/vapigen --quiet --library=fwupd \
   --directory=/github/workspace/build/obj-s390x-linux-gnu/libfwupd \
   --pkg=gio-2.0 --metadatadir=/github/workspace/build/libfwupd \
   /github/workspace/build/obj-s390x-linux-gnu/libfwupd/Fwupd-2.0.gir
error: Package `GLib-2.0' not found in specified Vala API directories or GObject-Introspection GIR directories