po/make-images: Drop unnecessary fontmap
This was causing problems building on Jessie, and turns out to be unused
anyway:
   AttributeError: 'gi.repository.PangoCairo' object has no attribute 'font_map_get_default'

Signed-off-by: Philip Withnall <withnall@endlessm.com>