Add missing build dependency to fwupdplugin-self-test
Parallel builds sometimes fail due to a header not having been generated
yet. Fix by adding fwupdplugin_rs_dep to the deps for fwupdplugin-self-test.

The build error can be reliably reproduced like so:

```
$ meson setup build
$ cd build
$ ninja libfwupdplugin/fwupdplugin-self-test.p/fu-self-test.c.o
[...snip...]
In file included from ../libfwupdplugin/fu-archive-firmware.h:10,
                 from ../libfwupdplugin/fwupdplugin.h:13,
                 from ../libfwupdplugin/fu-self-test.c:11:
../libfwupdplugin/fu-archive.h:12:10: fatal error: fu-archive-struct.h: No such file or directory
   12 | #include "fu-archive-struct.h"
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.
```