trivial: fix build with uclibc
We need to include stddef.h before scsi/sg.h for builds to work
with uclibc.

Fixes:
In file included from ../libfwupdplugin/fu-block-device.c:12:
/usr/include/scsi/sg.h:38:3: error: unknown type name ‘size_t’
   38 |   size_t iov_len;             /* Length in bytes  */
      |   ^~~~~~

In file included from ../plugins/ata/fu-ata-device.c:9:
/usr/include/scsi/sg.h:38:3: error: unknown type name ‘size_t’
   38 |   size_t iov_len;             /* Length in bytes  */
      |   ^~~~~~

In file included from ../plugins/scsi/fu-scsi-device.c:9:
/usr/include/scsi/sg.h:38:3: error: unknown type name ‘size_t’
   38 |   size_t iov_len;             /* Length in bytes  */
      |   ^~~~~~